#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Alpha directories
ROM_DIR="$HOME/repo/alpha"
ROM_PRODUCT_DIR="$ROM_DIR/out/target/product"
ROM_COMMON_DIR="$ROM_PRODUCT_DIR/msm8998-common"

if ! check_dir "$ROM_DIR" || ! cd "$ROM_DIR"; then
    exit_timestamp 1
fi

source build/envsetup.sh

# Default properties
TARGET_BUILD_PACKAGE=3
BUILD_DEVICE=dumpling
BUILD_TYPE=userdebug
RELEASE_VER=ap1a

#
# Build functions
#

alpha_build() {
    decho "Building AlphaDroid: $1 - $2 TARGET_BUILD_PACKAGE=$TARGET_BUILD_PACKAGE"
    export TARGET_BUILD_PACKAGE
    lunch lineage_$1-$RELEASE_VER-$2
    make bacon -j$(nproc)
    if [[ $1 == "dumpling" ]] && [[ $TARGET_BUILD_PACKAGE == "3" ]]; then
        SHARED_CP_ROM=true
    fi
    ROM_OUT=$(find $ROM_PRODUCT_DIR/$1/Alpha*.zip)
    rom_copy_target "$@"
}

alpha_build_gms() {
    TARGET_BUILD_PACKAGE=3
    alpha_build "$@"
}

alpha_build_vanilla() {
    TARGET_BUILD_PACKAGE=1
    alpha_build "$@"
}

alpha_build_both() {
    alpha_build_gms "$@"
    alpha_build_vanilla "$@"
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    BUILD_DEVICE="$2"
                    shift
                fi
            ;;            
            -t|--type)
                if check_valid "$2"; then
                    BUILD_TYPE="$2"
                    shift
                fi
            ;;
            -b|--build)
                if check_valid "$2"; then
                    TARGET_BUILD_PACKAGE="$2"
                    shift
                fi
            ;;
            -a|--all)
                BUILD_ALL=y
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $BUILD_ALL == "y" ]]; then
    DEVICES_LIST=(
        "dumpling"
        "cheeseburger"
    )
    for DEVICE in ${DEVICES_LIST[@]}; do
        alpha_build_both $DEVICE $BUILD_TYPE
    done
    exit_timestamp 0
fi

alpha_build $BUILD_DEVICE $BUILD_TYPE

exit_timestamp 0