#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Alpha directories
readonly ROM_DIR="$HOME/repo/alpha"

if ! check_dir "$ROM_DIR" || ! cd "$ROM_DIR"; then
    exit_timestamp 1
fi

source build/envsetup.sh

# Default properties
TARGET_BUILD_PACKAGE=3
build_device=dumpling
build_type=user
release_ver=ap2a

#
# Build functions
#

alpha_build() {
    local target_device=$1

    decho "Building AlphaDroid: $target_device - $build_type TARGET_BUILD_PACKAGE=$TARGET_BUILD_PACKAGE"
    export TARGET_BUILD_PACKAGE
    lunch lineage_$target_device-$release_ver-$build_type
    make bacon -j$(nproc)
    if [[ $target_device == "dumpling" ]] && [[ $TARGET_BUILD_PACKAGE == "3" ]]; then
        shared_cp_rom=true
    fi
    rom_copy_and_clean "Alpha" $target_device $build_type
}

alpha_build_gms() {
    TARGET_BUILD_PACKAGE=3
    alpha_build "$@"
}

alpha_build_vanilla() {
    TARGET_BUILD_PACKAGE=1
    alpha_build "$@"
}

alpha_build_both() {
    alpha_build_gms "$@"
    alpha_build_vanilla "$@"
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    build_device="$2"
                    shift
                fi
            ;;            
            -t|--type)
                if check_valid "$2"; then
                    build_type="$2"
                    shift
                fi
            ;;
            -b|--build)
                if check_valid "$2"; then
                    TARGET_BUILD_PACKAGE="$2"
                    shift
                fi
            ;;
            -a|--all)
                build_all=y
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $build_all == "y" ]]; then
    for device in ${devices_list[@]}; do
        alpha_build_both $device
    done
    exit_timestamp 0
fi

alpha_build $build_device

exit_timestamp 0