#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Derp directories
readonly ROM_DIR="$HOME/repo/derp"

if ! check_dir "$ROM_DIR" || ! cd "$ROM_DIR"; then
    exit_timestamp 1
fi

source build/envsetup.sh

# Default properties
build_device=dumpling
build_type=userdebug

#
# Build functions
#

derp_build() {
    local target_device=$1

    decho "Building DerpFest: $target_device - $build_type"
    lunch derp_$target_device-$build_type
    mka derp
    if [[ $target_device == "dumpling" ]]; then
        shared_cp_rom=true
    fi
    rom_copy_target "Derp" $build_type
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    build_device="$2"
                    shift
                fi
            ;;            
            -t|--type)
                if check_valid "$2"; then
                    build_type="$2"
                    shift
                fi
            ;;
            -a|--all)
                build_all=y
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $build_all == "y" ]]; then
    for device in ${devices_list[@]}; do
        derp_build $device
    done
    exit_timestamp 0
fi

derp_build $build_device

exit_timestamp 0