#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Rising directories
ROM_DIR="$HOME/repo/rising"
ROM_PRODUCT_DIR="$ROM_DIR/out/target/product"
ROM_COMMON_DIR="$ROM_PRODUCT_DIR/msm8998-common"

if ! check_dir "$ROM_DIR" || ! cd "$ROM_DIR"; then
    exit_timestamp 1
fi

source build/envsetup.sh

# Default properties
WITH_GMS=false
build_device=dumpling
build_type=user
build_cmd=b

#
# Build functions
#

rising_build() {
    decho "Building RisingOS: $1 - $build_type WITH_GMS=$WITH_GMS"
    export WITH_GMS
    riseup $1 $build_type
    rise $build_cmd
    if [[ $1 == "dumpling" ]] && [[ $WITH_GMS == "true" ]]; then
        shared_cp_rom=true
    fi
    # Target product filename; see rom_copy_target
    rom_target="$ROM_PRODUCT_DIR/$1/Rising"
    rom_copy_target $build_type
}

rising_build_gms() {
    WITH_GMS=true
    rising_build "$@"
}

rising_build_vanilla() {
    WITH_GMS=false
    rising_build "$@"
}

rising_build_both() {
    rising_build_gms "$@"
    rising_build_vanilla "$@"
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    build_device="$2"
                    shift
                fi
            ;;            
            -t|--type)
                if check_valid "$2"; then
                    build_type="$2"
                    shift
                fi
            ;;
            -g|--google)
                WITH_GMS=true
            ;;
            -a|--all)
                build_all=y
            ;;
            -s|--sign)
                build_cmd=sb
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $build_all == "y" ]]; then
    for device in ${devices_list[@]}; do
        rising_build_both $device
    done
    exit_timestamp 0
fi

rising_build $build_device

exit_timestamp 0