#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

script_dir=$(dirname $0)
if ! check_file "$script_dir/setup_env"; then
    decho "setup_env must be present in $script_dir!"
    exit_timestamp 1
fi
source $script_dir/setup_env

build_init

# Lineage directories
readonly ROM_NAME="lineage"
readonly ROM_DIR="$(pwd)"

if [[ -z $(echo $ROM_DIR | grep -i $ROM_NAME | grep -vi "${ROM_NAME}/") ]]; then
    decho "You are not in the right directory."
    exit_timestamp 1
fi

# Default properties
TARGET_BUILD_DYNAMIC=false
build_device=dumpling
build_type=user
build_number=bp4a
commonbranch=lineage-23.2-msm8998-4.19
support_nondyn_dyn=y

#
# Build functions
#

define_dynamic() {
    if [[ $TARGET_BUILD_DYNAMIC == "true" ]]; then
        dyn_branch=y
    else
        dyn_branch=n
    fi
}

lineage_build() {
    local target_device=$1

    decho "Building Lineage: $target_device - $build_type TARGET_BUILD_DYNAMIC=$TARGET_BUILD_DYNAMIC"

    define_dynamic
    setup_dynamic $commonbranch $target_device

    cleanup_path
    source build/envsetup.sh
    lunch lineage_$target_device-$build_number-$build_type
    m installclean
    lunch lineage_$target_device-$build_number-$build_type
    mka bacon -j$(nproc --all)
    restore_path

    rom_copy_and_clean "lineage" $target_device $build_type
}

lineage_build_dyn() {
    TARGET_BUILD_DYNAMIC=true
    lineage_build "$@"
}

lineage_build_nondyn() {
    TARGET_BUILD_DYNAMIC=false
    lineage_build "$@"
}

lineage_build_both() {
    lineage_build_nondyn "$@"
    lineage_build_dyn "$@"
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    build_device="$2"
                    shift
                fi
            ;;
            -t|--type)
                if check_valid "$2"; then
                    build_type="$2"
                    shift
                fi
            ;;
            -y|--dynamic)
                TARGET_BUILD_DYNAMIC=true
            ;;
            -a|--all)
                build_all=y
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $build_all == "y" ]]; then
    for device in ${devices_list[@]}; do
        lineage_build_both $device
    done
    exit_timestamp 0
fi

lineage_build $build_device

exit_timestamp 0
