#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

script_dir=$(dirname $0)
if ! check_file "$script_dir/setup_env"; then
    decho "setup_env must be present in $script_dir!"
    exit_timestamp 1
fi
source $script_dir/setup_env

build_init

# TWRP directories
readonly ROM_NAME="twrp"
readonly ROM_DIR="$(pwd)"

if [[ -z $(echo $ROM_DIR | grep -i $ROM_NAME | grep -vi "${ROM_NAME}/") ]]; then
    decho "You are not in the right directory."
    exit_timestamp 1
fi

# Default properties
build_device=cheeseburger_dumpling
build_type=eng

#
# Build functions
#

twrp_build() {
    local target_device=$1

    decho "Building TWRP: $target_device - $build_type"

    cleanup_path
    source build/envsetup.sh
    export ONEPLUS_DYNAMIC=true
    export ALLOW_MISSING_DEPENDENCIES=true
    lunch twrp_$target_device-$build_type
    m installclean
    lunch twrp_$target_device-$build_type
    mka recoveryimage -j$(nproc --all)
    restore_path

    twrp_copy_and_clean $target_device
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    build_device="$2"
                    shift
                fi
            ;;
            -t|--type)
                if check_valid "$2"; then
                    build_type="$2"
                    shift
                fi
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

twrp_build $build_device

exit_timestamp 0
