#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Derp directories
ROM_DIR="$HOME/repo/derp"
ROM_PRODUCT_DIR="$ROM_DIR/out/target/product"
ROM_COMMON_DIR="$ROM_PRODUCT_DIR/msm8998-common"

if ! check_dir "$ROM_DIR" || ! cd "$ROM_DIR"; then
    exit_timestamp 1
fi

source build/envsetup.sh

# Default properties
BUILD_DEVICE=dumpling
BUILD_TYPE=userdebug

#
# Build functions
#

derp_build() {
    decho "Building DerpFest: $1 - $BUILD_TYPE"
    lunch derp_$1-$BUILD_TYPE
    mka derp
    if [[ $1 == "dumpling" ]]; then
        SHARED_CP_ROM=true
    fi
    ROM_OUT=$(find $ROM_PRODUCT_DIR/$1/Derp*.zip)
    rom_copy_target "$@"
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    BUILD_DEVICE="$2"
                    shift
                fi
            ;;            
            -t|--type)
                if check_valid "$2"; then
                    BUILD_TYPE="$2"
                    shift
                fi
            ;;
            -a|--all)
                BUILD_ALL=y
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $BUILD_ALL == "y" ]]; then
    DEVICES_LIST=(
        "dumpling"
        "cheeseburger"
    )
    for DEVICE in ${DEVICES_LIST[@]}; do
        derp_build $DEVICE
    done
    exit_timestamp 0
fi

derp_build $BUILD_DEVICE

exit_timestamp 0