#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Kernel directories
KERNEL_PARENT_DIR=$HOME/kernel
SRC_DIR=$KERNEL_PARENT_DIR
OUT_DIR=$KERNEL_PARENT_DIR/output
REL_DIR=$KERNEL_PARENT_DIR/releases
TEST_DIR=$KERNEL_PARENT_DIR/test
SRT_DIR=$KERNEL_PARENT_DIR/scripts
ZIP_DIR=$KERNEL_PARENT_DIR/zip
LOG_DIR=$KERNEL_PARENT_DIR/buildlog
CLANG_DIR=$KERNEL_PARENT_DIR/toolchain/clang
GCC_DIR=$KERNEL_PARENT_DIR/toolchain/gcc

# Default properties
LOG=/dev/null
TEST_BUILD=y
DEBUG=n

JN=$(nproc)

SRCN="x-ft"
DC="msm8998_oneplus_debug_android_defconfig"
BRNCH_VER=$CURR_DATE
VER=1

AF="arch/arm64/configs"
ARCH="arm64"
SUBARCH=$ARCH
LWIMG="Image.gz-dtb"

CLANG_PATH="$CLANG_DIR/clang-r458507/bin"
GCC_PATH="${GCC_DIR}64/bin:${GCC_DIR}32/bin"
CC_PATH="$CLANG_PATH:$GCC_PATH"

C64="aarch64-linux-gnu-"
C32="arm-linux-gnueabi-"
CC="${C64}gcc"

#
# Build functions
#

define_log() {
    create_dir "$LOG_DIR"

    if ! check_file "$LOG"; then
        touch "$LOG_DIR/$KNAME.log"
    else
        echo "" > $LOG
    fi

    decho "Build start: $DATE_FULL" >> $LOG
    LOG="$LOG_DIR/$KNAME.log"
    {
        border
        echo "Last Commit:"
        echo $(git -C $SRC_DIR log -1 --pretty=%B)
        border
    } >> $LOG
}

define_kname() {
    KNAME="$SRCN-$SRC_BRNCH-$BRNCH_VER-$VER"
    KNAME_S="$SRCN-$BRNCH_VER-$VER"
}

define_clang() {
    CC="clang"

    CLANGMKP=" \
        LLVM=1 \
        LLVM_IAS=1 \
        "
}

define_debug() {
    DEBUGMKP="    \
        CONFIG_DEBUG_SECTION_MISMATCH=y \
        "
}

define_env() {
    border
    if [[ $SRC_BRNCH != "" ]]; then
        echo "Checking out to branch:"
        git checkout $SRC_BRNCH
    else
        CURRBRNCH="$(git rev-parse --abbrev-ref HEAD)"
        SRC_BRNCH=$CURRBRNCH

        echo "Using current branch:"
    fi
    echo $SRC_BRNCH
    border

    OUT=$OUT_DIR/$SRCN/$SRC_BRNCH
    BTI=$OUT/arch/$ARCH/boot

    define_kname

    if [[ $FORCE_VER != "y" ]]; then
        while [[ -f $LOG_DIR/$KNAME.log ]]
            do
            VER="$(($VER + 1))"
            define_kname
        done
    fi

    if [[ $CONFIGURE == "y" ]]; then
        echo "Configure only, no builds will be made..."
    else
        LOG=$LOG_DIR/$KNAME.log
        define_log
    fi

    if [[ $USE_CLANG == "y" ]]; then
        define_clang
    fi

    if [[ $DEBUG == "y" ]]; then
        define_debug
    fi

    CF="$($CC --version | head -1)"
    decho_log "Compiler being used: $CF"

    BUILD_STR="$SRCN release: $SRC_BRNCH-$BRNCH_VER-$VER built using $CF | Date: $DATE_FULL"

    MKP=" \
        $CLANGMKP \
        $DEBUGMKP \
        CC_WRAPPER=ccache \
        ARCH=$ARCH \
        SUBARCH=$SUBARCH \
        CROSS_COMPILE=$C64 \
        CROSS_COMPILE_ARM32=$C32 \
        LOCALVERSION=-$KNAME_S \
        O=$OUT \
        -j$JN \
        "

    if [[ $SRCN == "wsl2-kernel" ]]; then
        MKP=" \
            $CLANGMKP \
            $DEBUGMKP \
            LOCALVERSION=-$KNAME_S \
            O=$OUT \
            -j$JN \
            "
    fi

    decho "Make variables: $MKP" >> $LOG
}

build_func() {
    cd $SRC_DIR

    define_env

    if create_dir "$OUT"; then
        time make_cmd clean
        time make_cmd mrproper 
    fi

    if [[ $CONFIGURE == "y" ]]; then
        time make_cmd $DC menuconfig
        cp -v $OUT/.config $SRC_DIR/$AF/$DC
        decho "Copied .config to $DC"
        exit 0
    fi

    time make_cmd $DC

    if [[ $SRCN == "wsl2-kernel" ]]; then
        return
    fi

    if [[ $MAKE_ONLY == "y" ]]; then
        decho_log "Done generating .config at $OUT"
        code $OUT/.config
        exit 0
    fi

    time make_cmd
}

export_img() {
    if [[ $SRCN == "wsl2-kernel" ]]; then
        decho "Copying $BTI/$LWIMG to $C_USER_DIR/WSL"
        cp $BTI/$LWIMG $C_USER_DIR/WSL/$KNAME_S
        code $C_USER_DIR/.wslconfig
        return
    fi

    if ! check_dir $ZIP_DIR; then
        decho_log "There's no zip directory, abort!"
        exit 1
    fi

    cd $ZIP_DIR

    create_dir $PUSH_DIR

    mv -f $BTI/$LWIMG $ZIP_DIR
    touch version

    {
        echo "$SRCN kernel by ederekun"
        border
        echo "Build code: $SRC_BRNCH-$BRNCH_VER-$VER"
        echo "Date: $DATE_FULL"
    } >> version

    zip_image $PUSH_DIR/$KNAME
    create_dir $SHARED_TEST_DIR/builds
    cp $PUSH_DIR/$KNAME.zip $SHARED_TEST_DIR/builds/

    rm -f $LWIMG
    rm -f version
}

main_func() {
    if ! check_dir $SRC_DIR; then
        decho_log "Abort, source directory must exist."
        exit 1
    fi

    build_func

    if check_file "$BTI/$LWIMG"; then
        export_img
    fi

    decho_log "Build done: $DATE_FULL"
    decho "$BUILD_STR"
    create_dir $SHARED_TEST_DIR/logs
    cp $LOG $SHARED_TEST_DIR/logs/
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -s|--source)
                if check_valid "$2"; then
                    SRCN="$2"
                    shift
                fi
            ;;
            -b|--branch)
                if check_valid "$2"; then
                    SRC_BRNCH="$2"
                    shift
                fi
            ;;
            -v|--version)
                if check_valid "$2"; then
                    FORCE_VER=y
                    VER="$2"
                    shift
                fi
            ;;
            -cl|--clang)
                USE_CLANG=y
            ;;
            -a|--all)
                BUILD_ALL=y
            ;;
            -c|--configure)
                CONFIGURE=y
            ;;
            -r|--release)
                TEST_BUILD=n
            ;;
            -d|--debug)
                DEBUG=y
            ;;
            -mo|--make-only)
                MAKE_ONLY=y
            ;;
        esac
        shift
    done
}

param_main_func() {
    param_func "$@"
    main_func
}

#
# Build start
#

decho "Executing build script..."

param_func "$@"

SRC_DIR=$SRC_DIR/$SRCN

if [[ $TEST_BUILD == "y" ]]; then
    PUSH_DIR=$TEST_DIR
else
    PUSH_DIR=$REL_DIR
fi

if [[ $SRCN == "x-ft" ]]; then
    USE_CLANG=y
    export PATH="/usr/local/bin:$CC_PATH:$PATH"
    main_func
    exit 0
fi

if [[ $SRCN == "wsl2-kernel" ]]; then
    AF="arch/x86/configs"
    DC="KCONFIG_CONFIG=$AF/config-wsl-x86"
    ARCH="x86"
    LWIMG="bzImage"
    USE_CLANG=y
    export PATH="/usr/lib/ccache:$PATH"
    main_func
    exit 0
fi

decho "SRCN=$SRCN is unknown, please define in $0!"

exit 1
