#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

# Rising directories
ROM_DIR="$HOME/repo/rising"
ROM_PRODUCT_DIR="$ROM_DIR/out/target/product"
ROM_COMMON_DIR="$ROM_PRODUCT_DIR/msm8998-common"

if ! check_dir "$ROM_DIR" || ! cd "$ROM_DIR"; then
    exit_timestamp 1
fi

source build/envsetup.sh

# Default properties
WITH_GMS=false
BUILD_DEVICE=dumpling
BUILD_TYPE=user
BUILD_CMD=b

#
# Build functions
#

rising_build() {
    decho "Building RisingOS: $1 - $BUILD_TYPE WITH_GMS=$WITH_GMS"
    export WITH_GMS
    riseup $1 $BUILD_TYPE
    rise $BUILD_CMD
    if [[ $1 == "dumpling" ]] && [[ $WITH_GMS == "true" ]]; then
        SHARED_CP_ROM=true
    fi
    # Target product filename; see rom_copy_target
    ROM_TARGET="$ROM_PRODUCT_DIR/$1/Rising"
    rom_copy_target $BUILD_TYPE
}

rising_build_gms() {
    WITH_GMS=true
    rising_build "$@"
}

rising_build_vanilla() {
    WITH_GMS=false
    rising_build "$@"
}

rising_build_both() {
    rising_build_gms "$@"
    rising_build_vanilla "$@"
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -d|--device)
                if check_valid "$2"; then
                    BUILD_DEVICE="$2"
                    shift
                fi
            ;;            
            -t|--type)
                if check_valid "$2"; then
                    BUILD_TYPE="$2"
                    shift
                fi
            ;;
            -g|--google)
                WITH_GMS=true
            ;;
            -a|--all)
                BUILD_ALL=y
            ;;
            -s|--sign)
                BUILD_CMD=sb
            ;;
        esac
        shift
    done
}

#
# Build start
#

param_func "$@"

if [[ $BUILD_ALL == "y" ]]; then
    for device in ${ROM_DEVICES_LIST[@]}; do
        rising_build_both $device
    done
    exit_timestamp 0
fi

rising_build $BUILD_DEVICE

exit_timestamp 0