#!/bin/bash

# SPDX-FileCopyrightText: 2024 Edrick Sinsuan
# SPDX-License-Identifier: Apache-2.0

source setup_env

if ! check_file "build/envsetup.sh"; then
    decho "Call this script in the ROM's root directory!"
    exit_timestamp 1
fi

readonly ROM_ROOT="$(pwd)"

is_whitelisted() {
    local white_list_tmp=$white_list
    white_list=$white_list_default # Reset the list after patch
    for rom in ${white_list_tmp[@]}; do
        if [[ ! -z $(echo $ROM_ROOT | grep -i $rom) ]]; then
            return 0
        fi
    done
    return 1
}

is_blacklisted() {
    local black_list_tmp=$black_list
    black_list=$black_list_default # Reset the list after patch
    for rom in ${black_list_tmp[@]}; do
        if [[ ! -z $(echo $ROM_ROOT | grep -i $rom) ]]; then
            decho "Skipped patch..."
            return 0
        fi
    done
    return 1
}

patch_git() {
    local giturl=$1
    local sha1=$2
    local sha2=$3

    local commit_sha
    local commit_cnt

    if ! is_whitelisted; then
        return
    fi

    if is_blacklisted; then
        return
    fi

    decho "$dir"
    if check_dir "$dir" && cd "$dir"; then
        git fetch $giturl
        if [[ -z $sha2 ]]; then
            commit_sha="$sha1"
            commit_cnt="-n 1"
        else
            local conn='^..'
            commit_sha="$sha1$conn$sha2"
        fi
        decho "$(git log $commit_cnt --pretty=oneline $commit_sha)"
        git cherry-pick $commit_sha
        if [[ ! -z $sha2 ]]; then
            for ((i=0 ; i < ($(git rev-list --count $commit_sha) - 1) ; i++));
                do
                pause_script
                git cherry-pick --skip
            done
        else
            pause_script
        fi
        git cherry-pick --abort &> /dev/null
    fi
}

unpatch_git() {
    local sha1=$1
    local sha2=$2

    local commit_sha
    local commit_cnt

    if ! is_whitelisted; then
        return
    fi

    if is_blacklisted; then
        return
    fi

    decho "$dir"
    if check_dir "$dir" && cd "$dir"; then
        if [[ -z $sha2 ]]; then
            commit_sha="$sha1"
        else
            local conn='^..'
            commit_sha="$sha1$conn$sha2"
        fi
        decho "Reverting patches $commit_sha"
        git revert $commit_sha
        if [[ ! -z $sha2 ]]; then
            for ((i=0 ; i < ($(git rev-list --count $commit_sha) - 1) ; i++));
                do
                pause_script
                git revert --skip
            done
        else
            pause_script
        fi
        git revert --abort &> /dev/null
    fi
}

patch_single_curl() {
    local patchurl=$1

    if ! is_whitelisted; then
        return
    fi

    if is_blacklisted; then
        return
    fi

    decho "$dir"
    if check_dir "$dir" && cd "$dir"; then
        decho $patchurl
        curl $patchurl | git am -3
        pause_script
        git am --abort &> /dev/null
    fi
}

param_func() {
    while [[ $# -gt 0 ]]
        do
        key="$1"

        case $key in
            -s|--skip-pause)
                nopause=y
            ;;
        esac
        shift
    done
}

decho "This only needs to be called once if done cleanly and after a repo start!"

param_func "$@"

#
# 4.14 necessary patches
#

white_list_default=(
    "$ROM_ROOT"
)
black_list_default=(
)
white_list=$white_list_default
black_list=$black_list_default

# Patch qcom-caf for 4.14
dir=$ROM_ROOT/hardware/qcom-caf/common
patch_git "https://github.com/ederevx/android_hardware_qcom-caf_common a14" \
    "f346bb0364ff478bcc90efe0db0a2ec83f048226"

# Hookup TARGET_USES_GRALLOC1 - lineage
black_list=(
    "derp"
)
dir=$ROM_ROOT/vendor/lineage
patch_git "https://github.com/ederevx/android_vendor_lineage a14" \
    "d60c33fa98caa875cd7ba95ffb6e65090ef922f9"

# Hookup TARGET_USES_GRALLOC1 - derp
white_list=(
    "derp"
)
dir=$ROM_ROOT/vendor/derp
patch_git "https://github.com/ederevx/vendor_derp a14-derp" \
    "d9b9268e5beea02ddd15cc63635d2bce44d10f6c"

# Patch display-commonsys-intf for 4.14
dir=$ROM_ROOT/vendor/qcom/opensource/commonsys-intf/display
patch_git "https://github.com/ederevx/android_vendor_qcom_opensource_display-commonsys-intf a14" \
    "98e043abd0c9790469ad587a4ee1511108465f72" \
    "0858ef7d19da426164f5f31cd85778ce291fc771"

# Patch sepolicy-legacy-um for 4.14
dir=$ROM_ROOT/device/qcom/sepolicy-legacy-um
patch_git "https://github.com/ederevx/android_device_qcom_sepolicy a14" \
    "2049f8530b050b8d8e6bf81f30a9feb70d905961" \
    "98aee53ce762fc5e93a86c17a6a984cd5ddb6370"

#
# Various build fixes
#

# Define fake out directories
dir=$ROM_ROOT/build/make
patch_git "https://github.com/LineageOS/android_build lineage-21.0" \
    "ea73f271e00847ea25b1dc232416685e1a21cb1e"

# Allow bison
dir=$ROM_ROOT/build/soong
patch_git "https://github.com/ederevx/android_build_soong a14" \
    "6a4996614768c719b9559956289a11c91369e958"

# Add color channels for DeviceSettings
black_list=(
    "derp"
)
dir=$ROM_ROOT/frameworks/base
patch_git "https://github.com/ederevx/frameworks_base a14" \
    "bb487d4599e1a103f1881fe25acf2b63c8105356"

# Remove touchscreen gestures in Settings
black_list=(
    "derp"
)
dir=$ROM_ROOT/packages/apps/LineageParts
patch_git "https://github.com/ederevx/android_packages_apps_LineageParts a14" \
    "d0ccc35c0bd117e8841b0d414643c24ebc20a106"
black_list=(
    "derp"
)
dir=$ROM_ROOT/packages/apps/Settings
patch_git "https://github.com/ederevx/android_packages_apps_Settings a14" \
    "31187a64c9a5c49495651d11926edc5424a9473f"

# Fix sepolicy binder denials
dir=$ROM_ROOT/system/sepolicy
patch_git "https://github.com/ederevx/rising_android_system_sepolicy a14" \
    "99cb56c536b988430631bfcae3d877215e1416c8"

#
# Patches from https://github.com/OnePlus-5-T/local_manifests
#

# Fix USB DAC
dir=$ROM_ROOT/system/core
patch_single_curl "https://raw.githubusercontent.com/OnePlus-5-T/aosp_patches/a14/system/core/0001-libusbhost-improve-usb_device_open-handling.patch"
# Fix DSU
patch_single_curl "https://raw.githubusercontent.com/OnePlus-5-T/aosp_patches/a14/system/core/0002-first_stage_mount-Skip-dm-verity-setup-if-AVB-is-not.patch"
patch_single_curl "https://raw.githubusercontent.com/OnePlus-5-T/aosp_patches/a14/system/core/0003-Revert-libfiemap-Disable-loop-mapping-code.patch"

# Fix telephony
dir=$ROM_ROOT/frameworks/opt/telephony
patch_single_curl "https://raw.githubusercontent.com/OnePlus-5-T/aosp_patches/a14/frameworks/opt/telephony/0001-Restore-support-with-RadioConfig-1.0-dsds-clients.patch"
patch_single_curl "https://raw.githubusercontent.com/OnePlus-5-T/aosp_patches/a14/frameworks/opt/telephony/0002-Fallback_to_HAL_COMMAND_ALLOW_DATA.patch"

# Fix issues with GAPPS
dir=$ROM_ROOT/external/setupcompat
patch_single_curl "https://raw.githubusercontent.com/OnePlus-5-T/aosp_patches/a14/external/setupcompat/0001-Prevent-crash-with-improper-partner-config.patch"

exit_timestamp 0